
[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[font]
normal = { family="BlexMono Nerd Font Medium"}
offset = { x = 1, y = 0 }
size = 11

[window]
option_as_alt = "Both"

[general]
import = [
  "~/.config/alacritty/hardhacker.toml"
]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
